name: Continuos Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  continuos-Integration:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v3
      -name: Using Node.js
       uses: actions/setup-node@v2
       with:
          node-version: '20'
      -name: run install, build and test
        run: |
            npm install
            npm run build
            npm test